services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./templates_c:/var/www/html/templates_c
      - ./cache:/var/www/html/cache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped